name: choco

on:
  push:
    branches-ignore:
      - 'ga-ignore-**'
  pull_request:
    branches-ignore:
      - 'ga-ignore-**'

env :
  EXECUTABLES: "honey"

jobs:
  check_program_compilation:
      runs-on: ubuntu-latest
      timeout-minutes: 2
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: make
          run: make

        - name: make clean
          run: make clean

        - name: check execution
          run: |
            for i in $EXECUTABLES
            do
              echo "Testing $i"
              if [ -x $i ]
              then
                echo "Executable $i found"
              else
                echo "Executable $i not found"
                exit 1
              fi
            done

  run_tests:
    runs-on: ubuntu-latest
    needs: check_program_compilation
    container:
      image: tommoulard/criterion
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Run tests
        run: make tests_run
        timeout-minutes: 2
